server:
  port: 8080


spring:
  ## Profile Setting (is Default)
  application:
    name: SpotTag-dev
  config:
    activate:
      on-profile: dev


  ## DataBase (MySQL)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.22.78.239:5432/postgres
    username: postgres
    password: 43214321

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        naming:
          physical-strategy = org.hibernate.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    generate-ddl: true

# Logging Info
logging:
  level:
    org.springframework: debug

springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"