server:
  port: 8080


spring:
  ## Profile Setting (is Default)
  application:
    name: SpotTag-dev
  config:
    activate:
      on-profile: dev

  ## DataBase (MySQL)
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        naming:
          physical-strategy = org.hibernate.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    generate-ddl: true

# Logging Info
logging:
  level:
    org.springframework: debug

springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"